export const soups = [
  {
    id: 1,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 2,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 3,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 4,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 5,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 6,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 7,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
  {
    id: 8,
    name: "soup1",
    calories: "300",
    time: "15-20 min",
    allergy: "keto",
    price: 85,
    imgUrl: "https://picsum.photos/200/300",
  },
];

export default soups;
